apiVersion: v1
kind: Pod
metadata:
  name: sidecar-demo
spec:
  containers:
  - name: writer
    image: busybox
    command: ['sh','-c','while true; do date >> /logs/app.log; sleep 2; done']
    volumeMounts:
    - name: shared-logs
      mountPath: /logs

  - name: reader          # sidecar reading the same volume
    image: busybox
    command: ['sh','-c','tail -f /logs/app.log']
    volumeMounts:
    - name: shared-logs
      mountPath: /logs

  volumes:
  - name: shared-logs
    emptyDir: {}